name: GitHub Pages Validation
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main # Change this to your branch name if necessary

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Validate GitHub Pages
        run: |
          # Add any additional validation steps here
          
          # Example: Check if the generated site has any broken links
          bundle exec htmlproofer .
          
          # Validate HTML using W3C Markup Validation Service
          curl -H "Content-Type: text/html; charset=utf-8" --data-binary "@_site/index.html" https://validator.w3.org/nu/?out=json
